---
title: "Cross sectional data analysis- bTB bruc paper"
author: "Erin Gorsich"
date: "Feb 16, 2016"
output: html_document
---
  
```{r, data_readin, include=FALSE}
# packages used 
library(gplots)
setwd("~/Documents/postdoc_buffology/Last-Thesis-Chapter!!!!!!/final_datasets_copied_from_phdfolder")
source('~/GitHub/bTB-bruc-co-infection-ms/make_age_prev_plots.r')

# read in data prepared in cross_sectional_dataprep, groomed for my bTB statuses
data<-read.csv("cross_sectional_data_withdz_cleandisease_withfinal_Feb2016.csv")
data_nofinal<-data[data$final_capture=="0",]  # excludes 834-766 rows. 

# read in data prepared for Courtney's bTB statuses


```


Plot of prevalence in bTB+ and bTB- by agebin without final capture, Courtney's bTB
```{r, plot_ageprev_compare_c, echo=FALSE}
d<-data.frame(btb=data_nofinal$tbold , bruc=as.character(data_nofinal$bruc), age=data_nofinal$age_sel/12)
d2<-d[!is.na(d$btb),]
make_age_prev_plot(d2$btb, d2$bruc, d2$age, binsize=2)


```

Plot of prevalence in bTB+ and bTB- by agebin without final capture, My bTB
```{r, plot_ageprev_compare_m, echo=FALSE}

d<-data.frame(btb=data_nofinal$tb , bruc=as.character(data_nofinal$bruc), age=data_nofinal$age_sel/12)
make_age_prev_plot(d$btb, d$bruc, d$age, binsize=2)


```

Plot of prevalence in bTB+ and bTB- by agebin with final capture, Courtney's bTB
```{r, plot_ageprev_compare_cfinal, echo=FALSE}




```


Plot of prevalence in bTB+ and bTB- by agebin with final capture, My bTB
```{r, plot_ageprev_compare_mfinal, echo=FALSE}




```




